-- phpMyAdmin SQL Dump
-- version 4.1.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Lug 19, 2016 alle 22:22
-- Versione del server: 5.1.71-community-log
-- PHP Version: 5.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `my_hypcim`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `assistance`
--

CREATE TABLE IF NOT EXISTS `assistance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` text NOT NULL,
  `device-id` int(11) NOT NULL,
  `title` text NOT NULL,
  `answer` text NOT NULL,
  `service-id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=33 ;

--
-- Dump dei dati per la tabella `assistance`
--

INSERT INTO `assistance` (`id`, `category`, `device-id`, `title`, `answer`, `service-id`) VALUES
(1, 'Device', 29, 'How to reset Router', '	<p>There is a difference between <b>resetting</b> a router and <b>rebooting</b> a router. When you reboot your router that means you cycle the power to it. Resetting your router involves changing it back to its factory settings.</p>\r\n<p>Perhaps you have forgotten the password to your router and now you want to reset the password. First you need to reset the router back to its factory settings then you can use the default password to access your router.</p>\r\n\r\n\r\n<h2>How to Reboot your Router</h2> \r\n<p><b>Rebooting</b> a router means <b>cycling the power</b> to it. If you want to <b>reboot</b> your router, follow these steps:</p>\r\n\r\n<ul>\r\n	<li>Unplug the <b>power connector</b> from the back of the router and plug it back in.</li>\r\n	<li>Wait about <b>30 seconds</b> for the router to <b>reboot</b>.</li>\r\n	<li>Your internet connection will drop when your router is rebooted. If someone is using a computer on your network to access the internet, you may want to warn them.</li>\r\n</ul>\r\n<h2>How to Reset Your Router</h2>\r\n<p>When you <b>reset</b> your router the following <b>settings are changed</b>:</p>\r\n<ul>\r\n	<li><b>Router</b> username and password</li>\r\n	<li><b>Wi-Fi</b> username and password</li>\r\n	<li><b>ISP</b> username and password</li>\r\n	<li>Any <b>portforwards</b> you have set up</li>\r\n	<li>Any <b>firewall</b> settings you have made</li>\r\n	<li>Basically, any configuration changes that you have made to your router.</li>\r\n</ul>\r\n<p>As you can probably tell from the list above, <b>resetting</b> your router is serious business. Proceed with caution.</p>', -1),
(2, 'Device', 5, 'Reboot your phone', 'To reboot your phone switch it off', -1),
(3, 'Device', -1, 'Get help about your phone', 'How do i replace a lost,stolen or damaged phone?\r\n\r\nIf your phone is insured with CIM Covered, youâ€™ll need to make a claim\r\n\r\nDepending on how long you have left before your agreement ends, you might be eligible to upgrade early (which may involve a cost).Contact us to discuss your options.\r\n\r\nAlternatively, take a look at our range of great value Pay as you go phones', -1),
(4, 'Device', -1, 'Line Management', 'How can I reset my Cim router?\r\nYou can do this by using the reset button on the back of your router. Take a look at the Simple setup guide that came with your router for more details. Also check your product router website to see many instructions to do the reset. Normally the reset button is on the back of your router as image shows. ', -1),
(5, 'Services', -1, 'How do I make a complaint ', '<p> If youâ€™re unhappy and want to make a complaint, our customer service team is here to help. Contact us about your problems.', -1),
(6, 'Services', -1, 'How do I set up my new SIM card', '<p>If weâ€™ve sent you a new SIM, either because youâ€™ve upgraded, or had to replace a lost or damaged SIM, youâ€™ll need to do something called a SIM swap. This is so we can link your mobile number to your SIM on our network â€“ enabling you to use your phone. So a SIM swap essentially activates your new SIM.\r\n\r\nIf you already have a new SIM, you can activate it online. Please note your SIM will only be activated if itâ€™s been ordered through your account â€“ you canâ€™t activate a SIM given to you by someone else.\r\n\r\nIf you need a new SIM get in touch</p>', -1),
(7, 'Services', -1, 'How to start a live chat with support ', '<p>You can start a Live Chat to speak to an adviser 24 hours a day, 7 days a week.\r\n\r\nThe option for Live Chat will pop up across our site and throughout our Help and Support pages. Or you can choose that option on our Contact Us page â€“ which you can use to chat with an adviser at any time.\r\n\r\nWould you like to chat with an adviser now?\r\n\r\nIf youâ€™re a business customer, you can contact our customer services team. Alternatively, you can speak with your account manager or Prime Contact if you have one.</p>', -1),
(8, 'Device', -1, 'How do I transfer photos, contacts, videos and music from my old phone to my new phone?', '<p> Upgrading or changing your phone? Find out the best ways to transfer your contacts, photos, music and videos from your old phone to your new one:\r\n\r\n<ul>Android to Android\r\n<li>If you have a Microsoft Account you can use OneDrive\r\n<li>If you have a Google Account you can use Google Drive\r\n\r\nAndroid to iOS\r\n\r\n<li>You can download the Move to iOS app from the Play Store\r\n\r\niOS to iOS\r\n\r\n<li>If youâ€™re staying with Apple you can use iCloud to transfer content\r\niOS to Android\r\n<li>If you have a Microsoft Account you can use OneDrive\r\n<li>If you have  a Google Account you can use Google Drive\r\n\r\nWindows to (Android, iOS or Windows)\r\n\r\n<li>If you have a Microsoft Account you can use OneDrive\r\n<li>If you have a Google Account you can use Google Drive</p>', -1),
(9, 'Device', -1, '', '', -1),
(10, 'TV&Entertainment', -1, 'tv black screen', '<p> If you can not see one or more channels and the TV screen remains black, first, restart all the equipment such as modems, cable box, PC or mobile devices.\r\n\r\nIf you use a decoder control cable connections to power and check that the connection to the Ethernet network cable between the modem and decoder is correct and working. Also check that your fiber or ADSL connection is active and that the wires are inserted into the telephone wall jack.\r\n\r\nAfter checking the cables, we recommend that you verify the operation of Wi-Fi:\r\n\r\ncontrols receiving the Wi-Fi signal, and the signal strength on the device you are using to view the selected content\r\ntry to disconnect or disassociate all devices connected via Wi-Fi network and try to see the content with a single connected device\r\nSure, finally, which are not active on your Internet connection programs that can use the available bandwidth and generate traffic on the network, such as sharing software peer-to-peer.\r\n\r\nYou can control the speed of your Internet connection via the speed and know, so, if the bandwidth tests available on the line is adequate to the vision of the content.</p>', -1),
(11, 'TV&Entertainment', -1, 'Video problem', '<p> If the video presents the suqadrettamento problems while watching, first, restart all the equipment such as modems, cable box, PC or mobile devices.\r\n\r\nWe recommend that you verify the operation of Wi-Fi:\r\n\r\ncontrols receiving the Wi-Fi signal, and the signal strength on the device you are using to view the selected content\r\ntry to disconnect or disassociate all devices connected via Wi-Fi network and try to see the content with a single connected device\r\nSure, finally, which are not active on your Internet connection programs that can use the available bandwidth and generate traffic on the network, such as sharing software peer-to-peer and, after disabling any programs, try again to see the video.\r\n\r\nYou can control the speed of your Internet connection via the speed and know, so, if the bandwidth tests available on the line is adequate to the vision of the content.\r\n\r\nIf after all these checks, the problem persists, report a problem to Technical segnalation.</p>', -1),
(12, 'TV&Entertainment', -1, 'The audio is defective', '<p> If the video presents the audio reception problems, first, restart all the equipment such as modems, cable box, PC or mobile devices.\r\n\r\nWe recommend that you verify the operation of Wi-Fi:\r\n\r\ncontrols receiving the Wi-Fi signal, and the signal strength on the device you are using to view the selected content\r\ntry to disconnect or disassociate all devices connected via Wi-Fi network and try to see the content with a single connected device\r\nSure, finally, which are not active on your Internet connection programs that can use the available bandwidth and generate traffic on the network, such as sharing software peer-to-peer and, after disabling any programs, try again to see the video.\r\n\r\nYou can control the speed of your Internet connection via the speed and know, so, if the bandwidth tests available on the line is adequate to the vision of the content.\r\n\r\nIf after all these checks, the problem persists, report a problem to Technical segnalation.</p>', -1),
(13, 'TV&Entertainment', -1, 'Some videos are stuck', '<p> Se riscontri spesso rallentamenti o blocchi e interruzione durante la visione dei contenuti video, riavvia tutti gli apparati che utilizzi come modem, decoder, pc o device mobili. \r\n\r\nTi consigliamo di verificare il funzionamento della connessione Wi-Fi:\r\n\r\ncontrolla la ricezione del segnale Wi-Fi e la potenza del segnale sul dispositivo che stai utilizzando per vedere il contenuto scelto\r\nprova a disconnettere o disassociare tutti i dispositivi collegati tramite la rete Wi-Fi e prova a vedere il contenuto con un solo dispositivo collegato\r\nAssicurati, infine, che non siano attivi sulla tua connessione Internet programmi che possono utilizzare la banda disponibile e generare traffico sulla rete, come i software di condivisione peer-to-peer e, dopo aver disabilitato eventuali programmi, prova nuovamente a vedere il video.\r\n\r\nPuoi controllare la velocitÃ  della tua connessione Internet tramite il test di velocitÃ  e sapere, cosÃ¬, se la banda disponibile sulla linea Ã¨ adeguata alla visione del contenuto.  </p>', -1),
(14, 'Services', -1, 'registration', '<p>\r\nDuring registration of your CIM Mail, you can choose the username, which is the part of the email address before the @ hypcim.it, by following the rules:\r\n\r\nMinimum of 6 and maximum of 24 characters.\r\nYou can use letters, numbers, hyphens, underscores and dots.\r\nThe first character must necessarily be a letter.\r\nThe last character must necessarily be a letter or a number.\r\nYou can not use two consecutive points.\r\n</p>', -1),
(15, 'Services', -1, 'How quickly will i get online', 'When youâ€™re in an area with a strong 4G signal, you can expect faster speeds. The number of people connected to our network at the same time also affects these speeds.\r\n\r\nCheck out our helpful hints and tips on coverage and speed', -1),
(16, 'Device', -1, 'error code 404', '<p> This is an internet error message rather than a problem with your phone. It means â€˜page not foundâ€™ - which is normally because the page youâ€™re looking for has moved or disappeared, or youâ€™ve typed in the URL wrongly.</p>', -1),
(17, 'Device', -1, 'contact service error ', '<p>This means your phone has a problem talking to our network</p>', -1),
(18, 'Family and Home', -1, 'Antivirus ', '<p>To use the antivirus security software of CIM you must have:\r\n\r\nMicrosoft Windows 8, 8.1\r\nSupport for both the 32-bit version that for the 64-bit version with:\r\n\r\n2GHz or higher\r\n2 GB of RAM for 32-bit / 4 GB of RAM for 64-bit\r\n250MB of free hard disk space\r\nMicrosoftÂ® WindowsÂ® 7\r\nSupport for both the 32-bit version that for the 64-bit version with:\r\n\r\n2GHz or higher\r\n2 GB of RAM for 32-bit / 4 GB of RAM for 64-bit\r\n250MB of free hard disk space\r\n</p>', -1),
(19, 'Family and Home', -1, 'network security', '<p>Surfing the Internet, given the ubiquity and ease of access to the network, if not done carefully, it can be the cause of undesirable events such as:\r\n<ul>\r\n<li>Virus infections\r\n<li>receiving unwanted email (spam)\r\n<li>invasion of privacy\r\n<li>Access credentials theft (phishing)\r\n<li>the child safety threats\r\n\r\nIf you want to avoid computer viruses remember to use and update with some continuity dedicated software such as antivirus or firewalls that are able to identify and block dangerous attack.\r\n</p>', -1),
(21, 'Device', 19, 'iPhone mail', 'To add your mail account on iPhone, tap the Settings icon from the menu:  In the Settings:  choose the voice mail, contacts, calendars then Add Account ... from the list of providers \r\nTo add your mail account on iPhone, tap the Settings icon from the menu:  In the Settings:  choose the voice mail, contacts, calendars then Add Account ... from the list of providers  touch Add account Mail fill in the fields with your details of the Alice mailbox: Name: Enter a name of your choice; Address: your full address of the domain ; Password: enter your email password; Description: Enter a name to specify this account (Home, Office, ...).', -1),
(22, 'TV&Entertainment', 25, 'What is CIM Premium Online?', 'Football, Movies, TV and Infinity Series for TIM customers to 19 &euro; / month until 31/03/2017 to see when and where you want', -1),
(23, 'Home&Family', -1, 'CIM Tag', 'CIMTag, is the device that tells you about your friend s position on all fours and the things you care about most. Real-time follow his movements on your smartphone without ever losing sight.', -1),
(24, 'Service', -1, 'What is the Digital signature?', 'The trust must ensure that a digital signature is far superior to that of traditional handwritten signature. A private key known only by the person authorized to make use of it may even serve to prove their identity. They expect very interesting developments and CIM is in the foreground', -1),
(25, 'Device', 24, 'How can i connect my device to web?', 'You can do this manually by consulting the specific configuration guides for your device, available in the &quot;Set up online&quot;, selecting from the menu on the make and model.\r\nIf you do not remember the specific model of your Smartphone or Tablet, you can check it entering MyCIM Mobile. Your device will be automatically detected and you can display make and model.', -1),
(26, 'Device', -1, 'How can i activate a house line?', 'Request activation of a home phone line is very simple, you can:\r\napply online\r\ncall customer service fixed line 187\r\nbring to you at a CIM Shop.\r\nCheck the activation mode by consulting the various deals available on line.', -1),
(28, 'Device', -1, 'What is CIMreading?', 'CIMreading is the CIM Store that allows you to purchase and read books, newspapers and magazine on PC, Tablet and Smartphone.\r\nThe content available on the store are:\r\n11 national and sports newspapers, complete with attachments and local editions, available for weekly or monthly subscription on your PC, Tablet or Smartphone, to follow the information from early in the morning\r\nover 50 Magazine in single copy or subscription, to discover new trends and new destinations, follow the gossip and current\r\nover 75,000 books including the best seller, Mystery, romance, classics, and more, to pass the time reading a good book.', -1),
(29, 'Home&Family', -1, 'How can i get CIMreading?', 'They accept all the credit cards VISA, MasterCard, American Express, including prepaid and Postepay.\r\nThe number of credit card can be inserted at the time of purchase or configured previously between the payment instruments, while recording at the store or later in your profile.\r\nThis will allow you to buy your eBooks even when you are on the move, that is, if you access the store from CIMreading Tablet or Smartphone. In any case, to ensure your safety you will be always requested the inclusion of the security code of your credit card.\r\nWarning: If you purchase a subscription with a credit card, you can change the credit card stored in your profile at any time, provided that there is always a memorized, otherwise the subscription renewal will fail fine and the service will be turned off .(smart life)', -1),
(30, 'Service', -1, 'What is the Digital signature?', 'The trust must ensure that a digital signature is far superior to that of traditional handwritten signature. A private key known only by the person authorized to make use of it may even serve to prove their identity. They expect very interesting developments and CIM is in the foreground(smart life)', -1),
(31, 'TV&Entertainment', -1, 'What is CIM Premium Online?', 'Football, Movies, TV and Infinity Series for TIM customers to 19 &euro; / month until 31/03/2017 to see when and where you want(smart life)', -1),
(32, 'Service', -1, 'what is CIM Tag?', 'CIMTag, is the device that tells you about your friend s position on all fours and the things you care about most. Real-time follow his movements on your smartphone without ever losing sight.(smart life)', -1);

-- --------------------------------------------------------

--
-- Struttura della tabella `devices`
--

CREATE TABLE IF NOT EXISTS `devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` text COLLATE utf8_unicode_ci NOT NULL,
  `prezzo` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `capacita` int(11) NOT NULL,
  `colore` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `features` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `box` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `img_1` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `img_2` text CHARACTER SET utf8 COLLATE utf8_bin,
  `img_3` text CHARACTER SET utf8 COLLATE utf8_bin,
  `categoria` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=54 ;

--
-- Dump dei dati per la tabella `devices`
--

INSERT INTO `devices` (`id`, `nome`, `prezzo`, `capacita`, `colore`, `features`, `box`, `img_1`, `img_2`, `img_3`, `categoria`) VALUES
(50, 'Samsung Galaxy TAB A 10.1', '349,90', 16, 'black,white', '<ul>\r\n<li> Operating System Android 6.0\r\n<li> Display 10.1 "TFT\r\n<li> Exynos 7870 Octa Core 1.6 GHz processor\r\n<li> 2GB RAM\r\n<li> Camera 2 Mpx\r\n</ul>', '<ul>\r\n<li>1x Samsung TAB A \r\n<li>1x charger usb 2.0\r\n<li>1x cable micro usb 2.0\r\n</ul>', 'http://hypcim.altervista.org/img/Galaxy_TAB_A_side_black.jpg', 'http://hypcim.altervista.org/img/Galaxy_TAB_A_rear_black.jpg', 'http://hypcim.altervista.org/img/Galaxy_TAB_A_front_white.jpg', 'Tablet'),
(51, 'Acer ICONIA W4 821', '299,90', 0, 'grey', '<li>8 with 8 - the Iconia W series with Windows 8 is a true multi-user tablet with easy access to personal apps and settings via live tiles, plus access to the Windows Store for even more\r\n<li>8 hours on the go - the Iconia W series houses the Intel Atom processor and packs enough battery life for up to 8 hours of 720p video playback\r\n<li>Flexible and productive - a trial version of Microsoft Office is supplied so you can edit Word, Excel and PowerPoint docs on the go', '<li>1x Iconia Tablet\r\n<li>1x Power Adapter\r\n<li>1x User Documentation/Media', 'http://hypcim.altervista.org/img/acer-iconia-w4-grigio-1.jpg', 'http://hypcim.altervista.org/img/acer-iconia-w4-grigio-2.jpg', 'http://hypcim.altervista.org/img/acer-iconia-w4-grigio-3.jpg', 'Tablet'),
(32, 'ZTE SPro 2', '699,90', 0, 'black', '<li>A highly advanced projector with 3 main functions including Smart Projection, WiFi Hotspot + Powerbank\r\n<li>A 5-inch LCD 720p HD res touch screen- download all of your favourite apps and games\r\n<li>6300 mAh massive battery, providing power to your phone, laptop and tablet\r\n<li>DLP Technology will project crisp and detailed images/ videos, with powerful sound from built-in speakers\r\n<li>High resolution of 1280*720 pixels and 200 lumens for clear and bright images, provide exceptional display quality', '<li>1 x ZTE SPRO2 Projector \r\n<li>1 x HDMI Cable \r\n<li>1 x Adapter \r\n<li>1 x Bag \r\n<li>1 x Remote Control\r\n\r\n', 'http://hypcim.altervista.org/img/zte+spro2+3_4dx.jpg', 'http://hypcim.altervista.org/img/zte+spro2+3_4sx.jpg', '', 'Smart Living'),
(35, '  Polar Loop Activity Tracker', '99,90', 0, 'black, blue', '<li>Accurately measures your activity 24/7 including steps and calories\r\n<li>Shows resting and sitting times as well as daily activities\r\n<li>Provides guidance and motivation, distance based on daily steps\r\n<li>Monitors quality of sleep, waterproof for swimming and shows time of day\r\n<li>Training diary on the Polar flow web service summarises all your activity both on the web and your mobile\r\n<li>Custom fit, unisex bracelet and rechargeable battery (with USB) with five days continuous use\r\n<li>Optional accessory Polar H6 or H7 HR sensor adds heart rate monitoring to workouts and shows if you''re burning fat or improving fitness', '<li>1x Polar loop 2 activity tracker\r\n<li>1x Custom USB cable\r\n<li>1x Tool\r\n<li>1x Get started guide', 'http://hypcim.altervista.org/img/Polar_loop_blk_760x760.png', 'http://hypcim.altervista.org/img/Polar_loop_blue760x760.png', '', 'Smart Living'),
(36, 'Samsung Gear VR', '129,90', 0, 'white', '<li>Ergonomic design.Compatible S6, S6 edge & S6 edge +.Experience immersive.Dedicated content.360 Â° vision.\r\n<li>Compatible with: Samsung S6, S6 edge/S6 edge plus\r\n<li>Manufacturer''s warranty: 1 year (S)\r\n<li>Language: French', '<li>1x Gear VR', 'http://hypcim.altervista.org/img/gear_vr_1_760x760.jpg', 'http://hypcim.altervista.org/img/gear_vr_2_760x760.jpg', 'http://hypcim.altervista.org/img/gear_vr_3_760x760.jpg', 'Smart Living'),
(37, 'Tecnoware ERA Plus 900', '79,90', 0, 'black', '<li>Product Dimensions: 10 x 28 x 14 cm ; 3.7 Kg\r\n<li>Boxed-product Weight: 3.7 Kg\r\n<li>Delivery information: We cannot deliver certain products outside mainland UK ( Details). We will only be able to confirm if this product can be delivered to your chosen address when you enter your delivery address at checkout.\r\n<li>Batteries 1 Nonstandard Battery batteries required. (included)', '<li>1x ERA Plus 900', 'http://hypcim.altervista.org/img/slider_era_plus_900_tecnoware_1.jpg', 'http://hypcim.altervista.org/img/slider_era_plus_900_tecnoware_2.jpg', 'http://hypcim.altervista.org/img/slider_era_plus_900_tecnoware_3.jpg', 'Network'),
(38, 'Chromecast', '39', 0, 'black', '<ul>\r\n<li> Streaming your Android/iOS phone\r\n<li> Connect wireless with your TV \r\n<li> Watch CIMVision \r\n</ul>', '<ul>\r\n<li>1x Chromecast \r\n<li>1x HDMI adapter \r\n<li>1x charger\r\n</ul>', 'http://hypcim.altervista.org/img/CHROMECAST-1.jpg', 'http://hypcim.altervista.org/img/CHROMECAST-2.jpg', '', 'Smart Living'),
(39, 'Repeater ZyXEL N300', '39', 0, 'white', '<li>Easily extends wireless coverage of the existing 802.11 b/g/n networks\r\n<li>Compact wallmount design for convenient placement\r\n<li>Simple setup with the easy-to-use wizard and WPS button\r\n<li>gnal strength LED indicates the best setup location\r\n<li>Ethernet port for connecting wired devices to the wireless network', '<li>1x ZyXEL WRE2205 Wireless N300 Range Extender/Repeater\r\nUser guide', 'http://hypcim.altervista.org/img/repeater-zyxel-n300-1.jpg', '', '', 'Network'),
(40, 'FRITZ!WLAN Repeater 1750E', '89,90', 0, 'white', '<ul>\r\n<li> It extends the wireless range of up to 1750 Mbit / s\r\n<li> WPS: install it by pressing a button\r\n<li> Compatible with Wi-Fi modem TIM\r\n<li> Gigabit LAN port\r\n<li> 5 years warranty \r\n</ul>', '<ul>\r\n<li> Wireless Range Extender\r\n<li> Cavo Ethernet\r\n<li> Guida rapida\r\n</ul>', 'http://hypcim.altervista.org/img/slider-repeater-fritz-1750e-01.jpg', 'http://hypcim.altervista.org/img/slider-repeater-fritz-1750e-02.jpg', 'http://hypcim.altervista.org/img/slider-repeater-fritz-1750e-03.jpg', 'Network'),
(41, 'ASUS RT-AC87U AC2400', '159', 0, 'black', '<li>Ultra-fast 802.11ac Wi-Fi router\r\n<li>Worlds first 4x4 MU-MIMO antenna\r\n<li>ASUSWRT graphical user interface for easy\r\n<li>Built-in USB 2.0 and USB 3.0 ports\r\n<li>AiProtection with Trend Micro', '<li>1x RT-AC87U Wireless-AC2400 Dual Band Gigabit Router\r\n<li>1x RJ-45 Lead\r\n<li>1x Power adapter\r\n<li>1x Quick start guide\r\n<li>1x Software Disk', 'http://hypcim.altervista.org/img/95307680-5abd-4da8-aff4-04c075310f64.png._CB306377648_.png', '', '', 'Network'),
(43, 'NETGEAR EX6150-100UKS AC1200', '59,90', 0, 'white', '<li>Extends 2.4 and 5 GHz Wi-Fi signals from existing Wi-Fi routers for accurate range\r\n<li>Simultaneous dual band Wi-Fi to extend your speed up to 1200 Mbps and reduce interference\r\n<li>External antennas for wider coverage\r\n<li>Two Wi-Fi modes to extend your existing Wi-Fi connection or create a Wi-Fi access point\r\n<li>1 Gigabit Ethernet port and FastLane feature provides high-speed Wi-Fi on both wireless bands and is ideal for HD gaming and video streaming', '<li>1x Netgear AC1200 WiFi Range Extender\r\n<li>1x User Documentation', 'http://hypcim.altervista.org/img/header-EX6150-top-photo-large.png', '', '', 'Network'),
(44, 'Fitbit Charge', '129,99', 0, 'black', '<ul>\r\n<li> 3-axis accelerometer\r\n<li> Altimeter\r\n<li> vibration motor\r\n<li> Display OLED\r\n<li> Battery life: up than 7 - 10 days\r\n<li> Battery Type: Lithium Polyme\r\n<li> Charging time: 1-2 hours\r\n<li> Waterproof\r\n<li Operating temperature: -15 Â° C to 45 Â° C\r\n<li> Maximum operating altitude: 9144 meters\r\n</ul>', '<ul>\r\n<li>1x Charge Cable\r\n<li>1x Key wireless synchronization\r\n</ul>\r\n', 'http://hypcim.altervista.org/img/simple.b-cssdisabled-png.h7f00310d787c49e7cce9ed4a3651c911.png', '', '', 'Smart Living'),
(49, 'Samsung Galaxy Note 10.1 4G LTE', '479', 16, 'black, white', '<li>Large display, providing multi-screen functionality to maximise efficiency in learning, work and creative environments\r\n<li>Ensuring intuitive multitasking and web browsing, Galaxy Note 10.1 runs on Android 4.0 and features a 1.4 GHz Quad-core processor\r\n<li>S Note - a unique and efficient tool that lets you combine notes or sketches together with web content, images and other digital media', '<li>1x Galaxy Note 10.1 Handset\r\n<li>1x Travel Adapter Body\r\n<li>1x Conversion plug\r\n<li>1x 30-pin Data Cable\r\n<li>1x Stereo Headset\r\n<li>1x S-Pen\r\nS-Pen Tweezer + 5 tips\r\nQuick Start Guide', 'http://hypcim.altervista.org/img/prodotti_blocchetto_galaxy_note_101.png', '', '', 'Tablet'),
(45, 'Apple iPad Pro 9.7"', '1199,90', 256, 'black, white', '<li>256GB flash storage\r\n<li>9.7 inch (diagonal) LED-backlit Multi-Touch display\r\n<li>2048x1536 resolution at 264 pixels per inch (ppi)\r\n<li>Wide color and True Tone display\r\n<li>Fingerprint-resistant oleophobic coating', '<li>1x apple lightning cable\r\n<li>1x apple charge', 'http://hypcim.altervista.org/img/APPLE_IPAD_97_spacegrey_01.jpg', 'http://hypcim.altervista.org/img/APPLE_IPAD_97_spacegrey_03.jpg', 'http://hypcim.altervista.org/img/APPLE_IPAD_97_spacegrey_04.jpg', 'Tablet'),
(46, 'Huawei Mediapad T1 10 LTE', '249,90', 16, 'white', '<li>Product Type:Tablet\r\n<li>Operating System:Android 4.4.4 (KitKat)', '<li>1x lightning cable\r\n<li>1x charge', 'http://hypcim.altervista.org/img/huawei-t1-10-white-1.jpg', 'http://hypcim.altervista.org/img/huawei-t1-10-white-2.jpg', 'http://hypcim.altervista.org/img/huawei-t1-10-white-3.jpg', 'Tablet'),
(47, 'Samsung Galaxy S7', '699', 32, 'blues', '<ul>\r\n<li> Super AMOLED capacitive touchscreen, 16M colors 5.1 inch 1440 x 2560 pixels\r\n<li> Exynos 8890 Octa Quad-core 2.3 GHz Mongoose + quad-core 1.6 GHz Cortex-A53\r\n<li> 4 GB RAM\r\n<li> microSD, up to 256 GB\r\n<li> Camera 12 Mpx\r\n<li> 3000 mAh battery\r\n</ul>', '<ul>\r\n<li> 1 x usb type c cable\r\n<li> 1 x quick charger\r\n</ul>', 'http://hypcim.altervista.org/img/SAMSUNG_S7_Black_01.jpg', 'http://hypcim.altervista.org/img/SAMSUNG_S7_Black_02.jpg', 'http://hypcim.altervista.org/img/SAMSUNG_S7_Black_03.jpg', 'Smartphone'),
(48, 'Wi-Fi Bridge Technicolor', '79,90', 0, 'black ', '<ul>\r\n<li> Compact, vertical design\r\n<li> Wi-Fi AC 4x4 high performance\r\n<li> Association to the modem in WPS\r\n<li> Two Gigabit Ethernet ports\r\n<li> Status LEDs', '<ul>\r\n<li> Multimedia Connect\r\n<li> Power supply\r\n<li> Ethernet cable \r\n<li> Fast guide\r\n<li> Assurance of conformity \r\n<li> Safety sheet\r\n</ul>', 'http://hypcim.altervista.org/img/wifi-bridge-technicolor_01.jpg', '', '', 'Network'),
(27, 'Samsung Galaxy Tab S2 9.7', '319', 32, 'black,gold ', '<ul>\r\n<li> Super AMOLED capacitive touchscreen, 16M colors 9.7 inches 1536 x 2048 pixels\r\n<li> CPU Exynos 5433 Quad-core 1.9 GHz & quad-core 1.3 GHz\r\n<li> 3 GB RAM\r\n<li> microSD, up to 256 GB\r\n<li> Camera 8 Mpx\r\n<li> 5870 mAh battery\r\n</ul>', '<ul>\r\n<li>1 x microUSB v2.0\r\n<li>1 x charger usb 2.0\r\n</ul>', 'http://hypcim.altervista.org/img/bild0-7277381h53-075_1500_2.jpg', 'http://hypcim.altervista.org/img/81ydnatt2rl._sl1500__1_1_1.jpg', '', 'Tablet'),
(30, 'Samsung Smart TV 50" ', '899,90', 0, 'black', '<li>1x 50JU6400 - 50â€œ</li>\r\n<li>1x Ultra HD - 4K 3840 x 2160</li>\r\n<li>1x Soundbar HW-J250 inclusa</li>\r\n', '<li>1x Soundbar </li>', 'http://hypcim.altervista.org/img/samsung_smart_tv_50JU6400_slider_1.jpg', 'http://hypcim.altervista.org/img/samsung_smart_tv_50JU6400_slider_2.jpg', 'http://hypcim.altervista.org/img/samsung_smart_tv_50JU6400_slider_3.jpg', 'Smart Living'),
(28, 'Samsung Galaxy Gear S', '349', 0, 'black,blue', '<li>Multitask Watch</li>\r\n<li>Display 2â€ curved SuperAMOLED</li>\r\n<li>CPU DualCore 1GHz</li>', '<li>1x USB Battery charger</li>\r\n<li>1x Watch</li>\r\n<li>1x Manualr</li>', 'http://hypcim.altervista.org/img/samsung-galaxy-gear-s-1_0[1].jpg', 'http://hypcim.altervista.org/img/samsung-galaxy-gear-s-2_0[1].jpg', '', 'Smart Living'),
(29, 'Modem Fiber', '99', 0, 'white, red', '<li>Wi-Fi 802.11 b/g/n 2.4 Ghz or 5 Ghz</li>\r\n<li>Connect Smartphone, PC or Tablet</li>\r\n<li>Support ADSL/ADSL 2+/VDSL</li>\r\n<li>Interface 1x ADSL/VDSL - 1 x WAN 4 porte Gigabit Ethernet - 1 x Dect - 1 x PSTN 2 x FXSfor phone - 2 x USB for printers or memory</li>', '<li>1x Modem Fiber</li> \r\n<li>1x filter DSL </li>\r\n<li>2x Phone cables</li>\r\n<li>1x Ethernet yellow cable</li>\r\n<li>1x Charger</li>', 'http://hypcim.altervista.org/img/prodotti_modem_fibra_tim_01[1].jpg', '', '', 'Network'),
(22, 'LG G5 ', '399', 32, 'black', '<ul>\r\n<li> IPS LCD capacitive touchscreen, 16M colors 5.3 inches 1440 x 2560 pixels \r\n<li> CPU Qualcomm MSM8996 Snapdragon 820 Dual-core 2.15 GHz Kryo & dual-core 1.6 GHz Kryo\r\n<li> 3 GB RAM\r\n<li> microSD, up to 256 GB \r\n<li> Camera 16 Mpx\r\n<li> 2800 mAh battery\r\n</ul>', '<ul>\r\n<li> 1 x usb type c cable\r\n<li> 1 x quick charger\r\n</ul>', 'http://hypcim.altervista.org/img/71q-szonqdl._sl1500__2.jpg', 'http://hypcim.altervista.org/img/lg-g5-5__67511_zoom_1_1.jpg', '', 'Smartphone'),
(23, 'Motorola Moto G 2014', '169', 8, 'white', '<ul>\r\n<li> IPS LCD capacitive touchscreen, 16M colors 5.0 inches 720 x 1280 pixels \r\n<li> Qualcomm MSM8226 Snapdragon 400 Quad-core 1.2 GHz Cortex-A7\r\n<li> 1 GB RAM\r\n<li> Camera 8 Mpx\r\n<li> 2070 mAh battery\r\n</ul>', '<ul>\r\n<li>1 x micro usb 2.0 \r\n<li>1 x charger 2.0\r\n</ul>', 'http://hypcim.altervista.org/img/71urqzqiyml._sl1500__1.jpg', 'http://hypcim.altervista.org/img/7115n-myndl._sl1500__1.jpg', '', 'Smartphone'),
(24, 'iPhone SE ', '409', 16, 'pink', '<ul>\r\n<li> LED-backlit IPS LCD, capacitive touchscreen, 16M colors 4.0 inches 640 x 1136 pixels \r\n<li> CPU Apple A9\r\n<li> 2 GB RAM\r\n<li> Camera 12 Mpx\r\n<li> 1624 mAh battery \r\n</ul>', '<ul>\r\n<li>1 x apple lightning cable\r\n<li>1 x apple charge\r\n</ul>', 'http://hypcim.altervista.org/img/untitled6_2.png', 'http://hypcim.altervista.org/img/iphonese-rosegold-scene2-2016.png', '', 'Smartphone'),
(25, 'iPad Air 2 WiFi', '589', 128, 'black,white', '<ul>\r\n<li> LED-backlit IPS LCD, capacitive touchscreen, 16M colors 9.7 inches 1536 x 2048 pixels\r\n<li> CPU Apple A8X\r\n<li> 2 GB RAM\r\n<li> Camera 8 Mpx\r\n<li> Li-Po battery (27.3 Wh)\r\n</ul>', '<ul>\r\n<li>1 x apple lightning cable\r\n<li>1 x apple charge\r\n</ul>', 'http://hypcim.altervista.org/img/ipad-air-2-colors-space-gray_3_1.jpeg', 'http://hypcim.altervista.org/img/l_21962986_002_2_1.jpg', 'http://hypcim.altervista.org/img/ipad-air-2-colors-silver.jpeg', 'Tablet'),
(16, 'Asus ZenFone 2 ZE551ML', '229', 32, 'silver', '<ul>\r\n<li> Display IPS Full-HD 5.5 inch\r\n<li> CPU Intel Atom Z3580 64bit \r\n<li> RAM 4GB \r\n<li> Camera 13 megapixel \r\n<li> Battery 3000mAh\r\n</ul>', '<ul>\r\n<li>1 x cable usb 2.0\r\n<li>1 x charge usb\r\n</ul>', 'http://hypcim.altervista.org/img/91qoxrurgil._sl1500_.jpg', 'http://hypcim.altervista.org/img/91wa3fmupel._sl1500_.jpg', '', 'Smartphone'),
(18, 'Xiaomi Mi 5 ', '320', 32, 'black,white', '<ul>\r\n<li> Cpu SnapDragon 820 Kryo Quad Core 1.8 Ghz 64-Bit\r\n<li> Display 5.15 pollici Full HD	\r\n<li> 3 Gb Ram \r\n<li> Camera 16 Mpx	 	 \r\n<li> Battery 3000mAh\r\n</ul>', '<ul>\r\n<li>1 x cable usb type c \r\n<li>1 x quick charge 3.0\r\n</ul>', 'http://hypcim.altervista.org/img/xiaomi-mi5-white_0_3_600x600_3b590.jpg', 'http://hypcim.altervista.org/img/xiaomi-mi5-black_0_3_600x600_3b590.jpg', '', 'Smartphone'),
(19, 'iPhone 6S', '849', 128, 'black,white', '<ul>\r\n<li> Cpu Apple A9 64-Bit\r\n<li> Display 4.7 inch 750 x 1334 pixels\r\n<li> 2 Gb Ram\r\n<li> 12 Mpx\r\n<li> Battery 1715 mAh\r\n</ul>', '<ul>\r\n<li>1 x apple lightning cable\r\n<li>1 x apple charge  ', 'http://hypcim.altervista.org/img/74_23_1_1_1_1.jpg', 'http://hypcim.altervista.org/img/41_57_3.jpg', '', 'Smartphone'),
(20, 'Huawei Nexus 6P', '429', 64, 'black', '<ul>\r\n<li> 5.7 inches AMOLED capacitive touchscreen, 16M colors 1440 x 2560 pixels\r\n<li> CPU Quad-core 1.55 GHz Cortex-A53 & Quad-core 2.0 GHz Cortex-A57\r\n<li> 3 GB RAM\r\n<li> Camera 12.3 Mpx\r\n<li> Battery 3450 mAh\r\n</ul>\r\n', '<ul>\r\n<li>1 x usb type c cable\r\n<li>1 x quick charger\r\n</ul>', 'http://hypcim.altervista.org/img/nexus6p_o_graphite_h1_3_2.png', '', '', 'Smartphone'),
(21, 'Huawei P9', '469', 32, 'gold,gray,argent', '<ul>\r\n<li> IPS-NEO LCD capacitive touchscreen, 16M colors 5.2 inches 1080 x 1920 pixels\r\n<li> CPU Kirin 955 Quad-core 2.5 GHz Cortex-A72 & quad-core 1.8 GHz Cortex-A53\r\n<li> 3 GB RAM\r\n<li> microSD, up to 256 GB\r\n<li> Dual Camera 12 Mpx\r\n<li> 3000 mAh battery\r\n</ul>\r\n', '<ul> \r\n<li>1 x usb type c cable\r\n<li>1 x quick charger\r\n</ul>\r\n', 'http://hypcim.altervista.org/img/huawei-p9-gold-1_0_3_600x600_3b590.jpg', 'http://hypcim.altervista.org/img/huawei-p9-gray-1_0_3_600x600_3b590.jpg', 'http://hypcim.altervista.org/img/huawei-p9-silver-1_0_3_600x600_3b590.jpg', 'Smartphone'),
(52, 'D-Link SmartHome Starter Kit', '159.90', 0, 'white', '<li>Free service\r\n<li>Viewing from smartphone or tablet filming\r\n<li>Sending notifications of smartphone / tablet / e-mail\r\n<li>Wi-Fi connectivity via ADSL or 3G or 4G mobile modem', '<li>1x Charger\r\n<li>1x D-LINK webcam\r\n<li>1x  Movement sensor', 'http://hypcim.altervista.org/img/DLinkHD-2.jpg', 'http://hypcim.altervista.org/img/DLinkHD-3.jpg', 'http://hypcim.altervista.org/img/DLinkHD.jpg', 'Smart Living'),
(53, 'Samsung GALAXY NOTE PRO 12.2 Lte', '599', 64, 'back', '<li>Keyboard Book cover\r\n<li>Display: 12.2 "(2560x1600) TFT LCD\r\n<li>Operating System: Android 4.4 KitKat\r\n<li>Technology Quad view', '<li>1x Keyboard Book cover\r\n<li>1x charger\r\n<li>1x Samsung GALAXY NOTE PRO', 'http://hypcim.altervista.org/img/samsung-galaxy-note-pro-122-lte-black-1.jpg', 'http://hypcim.altervista.org/img/samsung-galaxy-note-pro-122-lte-black-2.jpg', 'http://hypcim.altervista.org/img/samsung-galaxy-note-pro-122-lte-black-3.jpg', 'Tablet');

-- --------------------------------------------------------

--
-- Struttura della tabella `promo`
--

CREATE TABLE IF NOT EXISTS `promo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` text NOT NULL,
  `device_id` int(11) NOT NULL,
  `details` text NOT NULL,
  `new_price` int(11) NOT NULL,
  `cat_promo` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=20 ;

--
-- Dump dei dati per la tabella `promo`
--

INSERT INTO `promo` (`id`, `nome`, `device_id`, `details`, `new_price`, `cat_promo`) VALUES
(5, 'Samsung Galaxy Tab S2 9.7', 27, '<li> 40 GB free Internet 4G for 30 days \r\n<li> CIM Card with 5 â‚¬ value', 15, 'Mobile'),
(4, 'iPhone 6s', 19, '<li> 1000 minutes of calls\r\n<li> 10 GB 4G\r\n<li> 500 SMS vs. all\r\n', 39, 'Mobile'),
(6, 'iPad Air 2 4G', 25, '<li> 40 GB free Internet 4G for 30 days\r\n<li> CIM Card with 10 â‚¬ value\r\n<li> 15 GB/month', 29, 'Mobile'),
(7, 'FRITZ!WLAN Repeater 1750E', 40, '<li> 36 installments if you have a CIM line', 2, 'Mobile+Home'),
(8, 'Samsung Galaxy TAB A PROMO', 50, '<li> 36 installaments if you have a CIM line\r\n<li> 40 GB free for 30 days\r\n<li> CIM Card with 5 â‚¬ value', 9, 'Mobile'),
(9, 'CIM Vision', 30, '<li>TV Series\r\n<li>Cartoons\r\n<li>Cinema', 5, 'Entertainment'),
(10, 'Pack CIMvision + Chromecast', 38, '<li>3 Months FREE CIMVision\r\n<li>Chromecast\r\n<li>6â‚¬/month ', 6, 'Entertainment'),
(12, 'Choose your Devise from 0â‚¬/month', 24, '<li>Internet every month\r\n<li>Internet 4GB\r\n<li>Smart 4GB SIM plus', 0, 'Mobile+Home'),
(13, 'Choose your Device from 15â‚¬/month', 53, '<li>Internet every month\r\n<li>internet 4GB\r\n<li>Smart 4GB SIM plus', 0, 'Mobile'),
(14, 'Only voice', 24, '<li>Unlimited National mobile calls', 5, 'Home'),
(15, 'Cim Voice & Internet', 20, '<li>20 Mbit/s speed\r\n<li>Unlimited calls', 7, 'Home'),
(16, 'CIM SMART FIBER', 48, '<li>From the Internet and television today with the high speed of the Fiber', 19, 'Home'),
(17, 'CIM SMART HOME', 52, '<li>Unlimited calls, Internet and TV from home + DLINK', 20, 'Mobile+Home'),
(19, 'CIMmusic', 18, '<li>Listen to millions of songs streaming of all kinds, anywhere, anytime', 15, 'Entertainment');

-- --------------------------------------------------------

--
-- Struttura della tabella `smartlife`
--

CREATE TABLE IF NOT EXISTS `smartlife` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `category` text NOT NULL,
  `device-id` int(11) NOT NULL,
  `description` text NOT NULL,
  `img` text NOT NULL,
  `price` varchar(11) NOT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=13 ;

--
-- Dump dei dati per la tabella `smartlife`
--

INSERT INTO `smartlife` (`id`, `title`, `category`, `device-id`, `description`, `img`, `price`) VALUES
(2, 'Netflix', 'TV&Entertainment', 30, 'TV series and movies from â‚¬ 7.99 / month, where you want and when you want, even the decoder CIMvision', 'http://hypcim.altervista.org/img/3.png', '7.99'),
(3, 'CIM Premium Online', 'TV&Entertainment', 45, '<li>Football, Movies, TV and Infinity Series for TIM customers to 19 â‚¬ / month until 31/03/2017 to see when and where you want', 'http://hypcim.altervista.org/img/4new-hungergames.png', '19'),
(5, 'Polar Loop Activity Tracker', 'Health', 35, '<li>In abbinamento con Polar sensore frequenza Cardiaca. Per chi desidera misurare la propria attivitÃ  24 ore su 24 ed essere guidato al raggiungimento di obiettivi giornalieri', 'http://hypcim.altervista.org/img/Polar_loop_blk_760x760.png', '8.99'),
(8, 'CIM Tag', 'Home&Family', -1, '<li>CIMTag, is the device that tells you about your friend''s position on all fours and the things you care about most.\r\nReal-time follow his movements on your smartphone without ever losing sight.', 'http://hypcim.altervista.org/img/localizza.jpg', '10'),
(7, 'D-Link SmartHome', 'Home&Family', 52, '<li>D-Link Smart Home Starter Kit offers you a chance to set up, control, monitor and automate your home wherever you are.', 'http://hypcim.altervista.org/img/DLinkHD-2.jpg', '5'),
(9, 'Digital signature', 'Service', -1, 'The trust must ensure that a digital signature is far superior to that of traditional handwritten signature. A private key known only by the person authorized to make use of it may even serve to prove their identity. They expect very interesting developments and CIM is in the foreground', 'http://hypcim.altervista.org/img/Firma_digitale.jpg', ''),
(10, 'Digital life or real life?', 'Service', -1, 'Access services, you pay for a subscription or a purchase, digital transactions are now part of our daily life and are gradually spreading. Reliability is a crucial component. Storage of money, as well as personal data, may be more convenient and also more secure', 'http://hypcim.altervista.org/img/facebook-una-scommessa-che-vale-100-miliardi-di-dollari-dollaro2_5.jpg', ''),
(12, 'Samsung Galaxy Gear S with SIM', 'Health', 28, '<li>An elegant curved Super AMOLED display for optimal fit, customizable screens and interchangeable straps to better express their own style', 'http://hypcim.altervista.org/img/samsung-galaxy-gear-s-r750-white-2.jpg', '349');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
